"""Compatibility facade for the Tesseract filesystem protocol."""

from piper_tesseract_foxy.protocol.contract import (
    COMMAND_RATE_HZ,
    HEALTH_FILENAME,
    JOINT_NAMES,
    MAX_BOOTSTRAP_START_LIMIT_TOLERANCE_RAD,
    MAX_CANDIDATE_VIEWS,
    MAX_CAPTURE_VIEWPOINTS,
    MAX_CONFIGURED_HOME_START_LIMIT_TOLERANCE_RAD,
    MAX_FILE_BYTES,
    MAX_FINAL_AIM_OFFSET_DEG,
    MAX_HEALTH_BYTES,
    MAX_OBSTACLES,
    MAX_POINTS_PER_SEGMENT,
    MAX_PROTOCOL_ACCELERATION_RAD_S2,
    MAX_PROTOCOL_VELOCITY_RAD_S,
    MAX_SEGMENTS,
    MOVEJ_NOMINAL_VELOCITY_RAD_S,
    PLAN_KINDS,
    PROVENANCE_SOURCES,
    QUEUE_NAMES,
    SAFE_ID,
    SCENE_OBSERVATION_MODES,
    SCHEMA_VERSION,
    SOURCE_REQUEST_ID,
    TIMING_POLICY,
    ContractError,
    angular_separation_deg,
    attach_digest,
    canonical_bytes,
    finite_vector,
    motion_limits_digest,
    require_sha256,
    sha256_file,
    sha256_value,
    target_ray_position_matches,
    trajectory_digest,
    validate_motion_limits,
    validate_plan_identity,
    validate_request,
    validate_response,
    verify_digest,
)
from piper_tesseract_foxy.protocol.spool import Spool

__all__ = [
    'COMMAND_RATE_HZ', 'HEALTH_FILENAME', 'JOINT_NAMES',
    'MAX_BOOTSTRAP_START_LIMIT_TOLERANCE_RAD', 'MAX_CANDIDATE_VIEWS',
    'MAX_CAPTURE_VIEWPOINTS', 'MAX_CONFIGURED_HOME_START_LIMIT_TOLERANCE_RAD',
    'MAX_FILE_BYTES', 'MAX_FINAL_AIM_OFFSET_DEG', 'MAX_HEALTH_BYTES',
    'MAX_OBSTACLES', 'MAX_POINTS_PER_SEGMENT',
    'MAX_PROTOCOL_ACCELERATION_RAD_S2', 'MAX_PROTOCOL_VELOCITY_RAD_S',
    'MAX_SEGMENTS', 'MOVEJ_NOMINAL_VELOCITY_RAD_S', 'PLAN_KINDS',
    'PROVENANCE_SOURCES', 'QUEUE_NAMES', 'SAFE_ID',
    'SCENE_OBSERVATION_MODES', 'SCHEMA_VERSION', 'SOURCE_REQUEST_ID',
    'TIMING_POLICY', 'ContractError', 'Spool', 'angular_separation_deg',
    'attach_digest', 'canonical_bytes', 'finite_vector',
    'motion_limits_digest', 'require_sha256', 'sha256_file', 'sha256_value',
    'target_ray_position_matches', 'trajectory_digest',
    'validate_motion_limits', 'validate_plan_identity', 'validate_request',
    'validate_response', 'verify_digest',
]
