"""Compatibility facade for mission contracts and state."""

from piper_mobile_manipulation.mission.core import (
    DEFAULT_DEADLINE_SEC,
    HEARTBEAT_TIMEOUT_SEC,
    MAX_DEADLINE_SEC,
    MAX_FEATURE_CAPTURES,
    MAX_OCCLUSION_ACTIONS,
    MAX_PENDING_MISSIONS,
    MISSION_QUEUE_COALESCE_SEC,
    REQUIRED_CAPTURES,
    TARGET_PROFILES,
    TASK_ID_PATTERN,
    TARGET_WORD_PATTERN,
    TERMINAL_PHASES,
    MissionPhase,
    MissionRegistry,
    MissionSession,
    TargetProfile,
    canonical_bytes,
    closest_pending_mission,
    mission_queue_ready,
    mission_target_distance_m,
    queued_cancel_result,
    sha256_value,
    target_prompt,
    validate_goal_payload,
)

__all__ = [
    'DEFAULT_DEADLINE_SEC',
    'HEARTBEAT_TIMEOUT_SEC',
    'MAX_DEADLINE_SEC',
    'MAX_FEATURE_CAPTURES',
    'MAX_OCCLUSION_ACTIONS',
    'MAX_PENDING_MISSIONS',
    'MISSION_QUEUE_COALESCE_SEC',
    'REQUIRED_CAPTURES',
    'TARGET_PROFILES',
    'TASK_ID_PATTERN',
    'TARGET_WORD_PATTERN',
    'TERMINAL_PHASES',
    'MissionPhase',
    'MissionRegistry',
    'MissionSession',
    'TargetProfile',
    'canonical_bytes',
    'closest_pending_mission',
    'mission_queue_ready',
    'mission_target_distance_m',
    'queued_cancel_result',
    'sha256_value',
    'target_prompt',
    'validate_goal_payload',
]
