"""Compatibility facade for scan-motion geometry and validation."""

from piper_mobile_manipulation.execution.motion import (
    CONTROLLER_COMMAND_LIMITS,
    MAX_CONFIGURED_HOME_FEEDBACK_LIMIT_TOLERANCE_RAD,
    MAX_FEEDBACK_LIMIT_TOLERANCE_RAD,
    URDF_JOINT_LIMITS,
    CollisionBox,
    PiperScanKinematics,
    approval_rejection_reason,
    attached_box_external_clearance_reasons,
    attached_box_world_corners,
    bootstrap_recovery_declaration_reasons,
    bootstrap_start_limit_recovery_reasons,
    camera_target_path_reasons,
    collision_segments,
    configuration_collision_reasons,
    configured_home_feedback_limit_reasons,
    energized_hold_target,
    feedback_joint_limit_reasons,
    finite_joints,
    interpolate_joint_path,
    joint_limit_reasons,
    load_accepted_hand_eye,
    load_conservative_joint_limits,
    minimum_self_segment_clearance,
    motor_control_reasons,
    motor_driver_states,
    orbit_camera_view,
    powered_motion_calibration_rejection,
    segment_distance,
    segment_intersects_expanded_box,
    startup_measured_hold_reference,
    validate_attached_box_external_clearance_path,
    validate_joint_path,
    validate_monotonic_self_clearance_escape,
)

__all__ = [
    'CONTROLLER_COMMAND_LIMITS',
    'MAX_CONFIGURED_HOME_FEEDBACK_LIMIT_TOLERANCE_RAD',
    'MAX_FEEDBACK_LIMIT_TOLERANCE_RAD', 'URDF_JOINT_LIMITS', 'CollisionBox',
    'PiperScanKinematics', 'approval_rejection_reason',
    'attached_box_external_clearance_reasons', 'attached_box_world_corners',
    'bootstrap_recovery_declaration_reasons',
    'bootstrap_start_limit_recovery_reasons', 'camera_target_path_reasons',
    'collision_segments', 'configuration_collision_reasons',
    'configured_home_feedback_limit_reasons', 'energized_hold_target',
    'feedback_joint_limit_reasons', 'finite_joints',
    'interpolate_joint_path', 'joint_limit_reasons', 'load_accepted_hand_eye',
    'load_conservative_joint_limits', 'minimum_self_segment_clearance',
    'motor_control_reasons', 'motor_driver_states', 'orbit_camera_view',
    'powered_motion_calibration_rejection', 'segment_distance',
    'segment_intersects_expanded_box', 'startup_measured_hold_reference',
    'validate_attached_box_external_clearance_path', 'validate_joint_path',
    'validate_monotonic_self_clearance_escape',
]
