"""Compatibility facade for target silhouette and envelope geometry."""

from piper_mobile_manipulation.perception.target_envelope import (
    AXIS_ANISOTROPY_RATIO,
    CAMERA_SURFACE_CLEARANCE_M,
    CAPTURE_MODEL_SEED_MAX_TRANSFORM_DELTA_SEC,
    CAPTURE_MODEL_SEED_SCHEMA_VERSION,
    CROPPED_TOO_CLOSE_DISTANCE_M,
    CROPPED_TOO_LARGE_DISTANCE_M,
    ENVELOPE_INFLATION_M,
    ENVELOPE_SCHEMA_VERSION,
    MAX_PROFILE_SECTIONS,
    MAX_SILHOUETTE_POINTS,
    SHAPE_SCHEMA_VERSION,
    TARGET_SILHOUETTE_CLIPPED,
    TargetSilhouetteClippedError,
    build_capture_model_seed,
    build_revolution_envelope,
    canonical_sha256,
    classify_centered_silhouette,
    clipped_shape_rejection,
    coverage_sphere_from_envelope,
    envelope_constrained_ray_interval,
    minimum_fov_standoff,
    point_to_envelope_distance,
    stamp_nanoseconds,
    trusted_silhouette_measurement,
    validate_capture_model_seed,
    validate_envelope,
    validate_shape_measurement,
    validate_shape_rejection,
)

__all__ = [
    'AXIS_ANISOTROPY_RATIO', 'CAMERA_SURFACE_CLEARANCE_M',
    'CAPTURE_MODEL_SEED_MAX_TRANSFORM_DELTA_SEC',
    'CAPTURE_MODEL_SEED_SCHEMA_VERSION', 'CROPPED_TOO_CLOSE_DISTANCE_M',
    'CROPPED_TOO_LARGE_DISTANCE_M', 'ENVELOPE_INFLATION_M',
    'ENVELOPE_SCHEMA_VERSION', 'MAX_PROFILE_SECTIONS',
    'MAX_SILHOUETTE_POINTS', 'SHAPE_SCHEMA_VERSION',
    'TARGET_SILHOUETTE_CLIPPED', 'TargetSilhouetteClippedError',
    'build_capture_model_seed', 'build_revolution_envelope',
    'canonical_sha256', 'classify_centered_silhouette',
    'clipped_shape_rejection', 'coverage_sphere_from_envelope',
    'envelope_constrained_ray_interval', 'minimum_fov_standoff',
    'point_to_envelope_distance', 'stamp_nanoseconds',
    'trusted_silhouette_measurement', 'validate_capture_model_seed',
    'validate_envelope', 'validate_shape_measurement',
    'validate_shape_rejection',
]
