uint8 START_SURVEY=0
uint8 CAPTURE_SURVEY=1
uint8 APPROVE_PLAN=2
uint8 CONFIRM_ACTION_COMPLETE=3
uint8 START_SCAN=4
uint8 ACKNOWLEDGE_VIEWPOINT=5
uint8 CAPTURE_VIEW=6
uint8 SKIP_VIEW=7
uint8 FINALIZE=8
uint8 CLEAR=9
uint8 ABORT=10

uint8 command
uint32 viewpoint_index
string reason
---
bool accepted
uint8 state
string state_name
string message
